name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd moya-FE
          git pull origin main
          
          # 기존 컨테이너 정지 및 제거
          docker stop moya-frontend-container || true
          docker rm moya-frontend-container || true
          docker rmi moya-fe || true
          
          # 새 이미지 빌드 및 실행
          docker build -t moya-fe .
          docker run -d -p 80:80 --name moya-frontend-container moya-fe
          
          # 컨테이너 상태 확인
          docker ps

